# Generated by Django 5.2.5 on 2025-09-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code_type',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login')], default='register', max_length=255),
        ),
    ]
