# Generated by Django 5.2.5 on 2025-10-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_magiclinktoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicLinkToken',
        ),
    ]
