# Generated by Django 5.2.5 on 2025-10-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_magiclinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='token',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
