# Generated by Django 5.2.5 on 2025-10-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverificationcode_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code_type',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('reset_password', 'Reset password')], default='register', max_length=255),
        ),
    ]
