# Generated by Django 5.2.5 on 2025-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_emailverificationcode_code_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='register_type',
            field=models.CharField(choices=[('email', 'Email/Password'), ('oauth', 'OAuth')], max_length=255, null=True),
        ),
    ]
