# Generated by Django 5.2.5 on 2025-12-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
