# Generated by Django 5.2.5 on 2025-12-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_phone_number_customuser_telegram_link'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
