# Generated by Django 5.2.5 on 2025-12-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_managers_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='register_type',
        ),
    ]
