# Generated by Django 5.2.5 on 2025-12-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_registertype_customuser_register_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
