# Generated by Django 5.2.5 on 2025-12-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_changed',
        ),
    ]
