# Generated by Django 5.2.5 on 2025-12-22 09:38

import users.querysets.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_customuser_password_changed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.querysets.user.CustomUserManager()),
            ],
        ),
    ]
