# Generated by Django 5.2.5 on 2025-08-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_slug_alter_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
