# Generated by Django 5.2.5 on 2025-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
