# Generated by Django 5.2.5 on 2025-08-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lesson_slug_material_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='assigned_at',
        ),
    ]
