# Generated by Django 5.2.5 on 2025-08-28 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_homework_assigned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='student',
        ),
        migrations.AddField(
            model_name='livesession',
            name='students',
            field=models.ManyToManyField(related_name='live_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
