# Generated by Django 5.2.5 on 2025-08-28 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_submissionreview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(fields=('lesson', 'title'), name='unique_lesson_homework_title'),
        ),
    ]
