# Generated by Django 5.2.5 on 2025-08-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_homework_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/'),
        ),
    ]
