# Generated by Django 5.2.5 on 2025-09-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_homeworksubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionreview',
            name='submission',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.homeworksubmission'),
        ),
    ]
