# Generated by Django 5.2.5 on 2025-12-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_icon_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.menu'),
        ),
    ]
