# Generated by Django 5.2.5 on 2025-12-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_menu_icon_id_alter_menu_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='icon_id',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
