# Generated by Django 5.2.5 on 2025-12-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_languageline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageline',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
