# Generated by Django 5.2.5 on 2026-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_languageline_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
