# Generated by Django 5.2.5 on 2026-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
